### ISSUE TITLE
Consider switching to unsigned for time_s and time_ms

### ISSUE THREAD

**Issue by dmolik** [jhunt/libvigor#10]
or rationalize negative time, I suppose in a network without being able to guarantee consistency across all nodes... but there was a need to measure time against other nodes, IE a negative ntp offset.

**Comment by jhunt** [comment]
Reasons against?

**Comment by dmolik** [comment]
yes, it is a function value change after all

**Comment by jhunt** [comment]
I think my original intent with a signed result was to handle invalid times as `-1`, but the 0 value works just as well for that, since nothing interesting happened at 1/1/1970 00:00:00 UTC (except for the start of time, of course).

What specific problem did you run into?

**Comment by jhunt** [comment]
Also, per **`time(3)`**:

```
 The time() function returns the value of time in seconds since 0 hours, 0
 minutes, 0 seconds, January 1, 1970, Coordinated Universal Time, without
 including leap seconds.  If an error occurs, time() returns the value
 (time_t)-1.
```

I'm not against this change, or a similar change to introduced signed versions of `time_s` and `time_ms`, just want to understand why, and have a good reason before breaking ABI.  Also, it should probably get queued with some other ABI-breaking changes to minimize churn.

**Comment by dmolik** [comment]
with a signed 32 bit, we will rollover unix time in 22 years, do we need to worry?

I mean I'll be 51, so I'll be working and my first kid will probably be in college. So, I'll need to be working, and still probably writing C code.

Kidding aside we can probably close this with a won't fix.
