### ISSUE TITLE
Bolo rfc support for data frames

### ISSUE THREAD

**Issue by dmolik** [jhunt/libvigor#13]
I think it makes sense to add the following macros to support type specific requirements set in the bolo-rfc

```
#define htonll(x) ((1==htonl(1)) ? (x) : ((uint64_t)htonl((x) & 0xFFFFFFFF) << 32) | htonl((x) >> 32))
#define ntohll(x) ((1==ntohl(1)) ? (x) : ((uint64_t)ntohl((x) & 0xFFFFFFFF) << 32) | ntohl((x) >> 32)) 
```

**Comment by jhunt** [comment]
PR?

**Comment by jhunt** [comment]
also, you might want to guard these with #ifdefs, since at least OS X has already defined these macros in `arpa/inet.h`
